- name: Copy join command
  ansible.builtin.copy:
    src: /tmp/worker_join_command
    dest: /tmp/worker_join_command
    mode: '0700'

- name: Join worker node
  ansible.builtin.shell: sh /tmp/worker_join_command > $HOME/worker_joined
  args:
    chdir: $HOME
    creates: worker_joined
