- hosts: all
  become: yes
  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_agent_server: 192.168.10.11
      zabbix_agent_serveractive: 192.168.10.11
      zabbix_api_server_host: zabbix.devops.com
      zabbix_api_server_port: 80
      zabbix_api_login_user: Admin
      zabbix_api_login_pass: zabbix
      zabbix_api_create_hostgroup: true
      zabbix_api_create_hosts: true
      zabbix_agent_host_state: present
      zabbix_host_groups:
        - Linux Servers
      zabbix_agent_link_templates:
        - Linux by Zabbix agent
      zabbix_agent_macros:
        - macro_key: apache_type
          macro_value: reverse_proxy
          macro_type: text
      zabbix_agent_tags:
        - tag: environment
          value: production
