- name: Copy join command
  ansible.builtin.copy:
    src: /tmp/control_join_command
    dest: /tmp/control_join_command
    mode: '0700'

- name: Join control node
  ansible.builtin.shell: sh /tmp/control_join_command > $HOME/control_joined
  args:
    chdir: $HOME
    creates: control_joined
