- name: Ensure nginx is installed
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true

- name: Add nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx

- name: Ensure Nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
