- name: Ensure etcd installed
  ansible.builtin.apt:
    pkg:
      - etcd-server
      - etcd-client
    update_cache: true

- name: Copy /etc/default/etcd config
  ansible.builtin.template:
    src: etcd.j2
    dest: /etc/default/etcd
    mode: 'u=rw,g=r,o=r'
  notify:
    - Restart etcd
