services:
  app1:
    build: ./app
    ports:
      - "8001:8000"
    environment:
      ID_INSTANCE: 1

  app2:
    build: ./app
    ports:
      - "8002:8000"
    environment:
      ID_INSTANCE: 2

  app3:
    build: ./app
    ports:
      - "8003:8000"
    environment:
      ID_INSTANCE: 3

  nginx:
    image: nginx:1.27.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/cache:/var/nginx/cache
    depends_on:
      - app1
      - app2
      - app3
